### PR TITLE
Judging Admin Panel Progress + misc fixes

### LINKED ISSUE #242: Judging Admin Panel Progress Indicator
## Description
* Add a percentage indicator to `/judging/admin` to show total progress of projects judged. Should be `# projects judged / # projects assigned`

### PR DESCRIPTION
**Pull request by jackyzha0**
closes #242

### CODE REVIEW

File: src/containers/JudgingPanel.js [hunk 1]
```diff
@@ -96,12 +126,15 @@ export default () => {
   const handleClick = async () => {
     setLoading(true)
     setGradedProjects(await getGradedProjects())
+    getStats().then(data => setStats(data))
     setLoading(false)
+    console.log(stats)
```
Comment (ianmah) [inline src/containers/JudgingPanel.js:131]: 🔪

**Review by ianmah — APPROVED** [review]
